version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /sdk
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /docs
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
