-- Initial schema, matching what Hibernate's ddl-auto=update had been generating.
-- Portable across PostgreSQL (real deployments) and H2 in PostgreSQL compatibility mode
-- (tests): plain VARCHAR/TEXT/TIMESTAMP WITH TIME ZONE, no dialect-specific types.
--
-- The payload/details columns are deliberately plain TEXT rather than JPA's @Lob - on
-- real PostgreSQL, Hibernate's schema validator expects @Lob String columns to be the
-- large-object oid type, not text, which is more trouble than it's worth for values that
-- are just longer strings. Dropping @Lob on those two entity fields (kept as plain
-- @Column(columnDefinition = "TEXT")) sidesteps the oid type entirely.

CREATE TABLE organizations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    api_key_hash    VARCHAR(255) NOT NULL UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE endpoints (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organizations (id),
    name                    VARCHAR(255) NOT NULL,
    url                     VARCHAR(255) NOT NULL,
    secret                  VARCHAR(255) NOT NULL,
    rate_limit_per_second   INTEGER NOT NULL DEFAULT 10,
    verified                BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at             TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_endpoints_organization_id ON endpoints (organization_id);

CREATE TABLE topics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    name            VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_topics_organization_name UNIQUE (organization_id, name)
);

CREATE TABLE subscriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id        BIGINT NOT NULL REFERENCES topics (id),
    endpoint_id     BIGINT NOT NULL REFERENCES endpoints (id),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_subscriptions_topic_endpoint UNIQUE (topic_id, endpoint_id)
);

CREATE INDEX idx_subscriptions_endpoint_id ON subscriptions (endpoint_id);

CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id    BIGINT NOT NULL REFERENCES topics (id),
    payload     TEXT NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_events_topic_id ON events (topic_id);

CREATE TABLE deliveries (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                BIGINT NOT NULL REFERENCES events (id),
    endpoint_id             BIGINT NOT NULL REFERENCES endpoints (id),
    status                  VARCHAR(20) NOT NULL,
    attempt_count           INTEGER NOT NULL DEFAULT 0,
    max_attempts            INTEGER NOT NULL DEFAULT 8,
    next_attempt_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    last_attempt_at         TIMESTAMP WITH TIME ZONE,
    last_response_status    INTEGER,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_deliveries_endpoint_id ON deliveries (endpoint_id);
CREATE INDEX idx_deliveries_status_next_attempt_at ON deliveries (status, next_attempt_at);

CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    action          VARCHAR(255) NOT NULL,
    details         TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_logs_organization_id ON audit_logs (organization_id);
